### ISSUE TITLE
[Enhancements] Different coloring for hover ?

### ISSUE THREAD

**Issue by Steelskinz** [Aedif/tactical-grid#1]
I believe it would be nice to have a different coloring for the hover on the tactical grid.
This could help to determine easily how far can a enemy move for example or other effects. 
Edit : I wanted to add that this module is actually a good addition, feel fresh and really interesting, good job !

**Comment by Aedif** [comment]
I don't think I quite understand what you mean. 

Instead of masking out (hiding) the grid do you want to simply change the surrounding color?

**Comment by Steelskinz** [comment]
Yeah, I'm using it to show my players (So controlled Tokens) where they can move basically, and I wish you could change the color of the grid when you hover an enemy token, like to know where it could move, but I don't think that might be possible. 
![image](https://user-images.githubusercontent.com/93941729/220450768-e343b75d-2107-47cf-bbc1-0fd169d4b34a.png)

**Comment by Aedif** [comment]
This is not trivial to do with the way the module is currently implemented. I might consider it in the future but not for now. Thanks for the suggestion though!

**Comment by Aedif** [comment]
This is now possible as of release [1.5.0](https://github.com/Aedif/tactical-grid/releases/tag/1.5.0)
