### ISSUE TITLE
[Bug] Drag Ruler Bug

### ISSUE THREAD

**Issue by cadowtin** [Aedif/tactical-grid#11]
Bug as described

- Have at least 2 people online
- One person uses drag ruler at all
- The other client now is stuck in a bugged state with distances up on their end till they also use drag ruler causing the bug on another client
![image](https://user-images.githubusercontent.com/79132112/230277494-63a67a48-ad89-4164-9430-debd31b3fe91.png)

**Comment by cadowtin** [comment]
It appears that bug is that Tactical Grid never removes the highlighted square on other clients only on the host client when the drag ruler part is done.

**Comment by cadowtin** [comment]
Also noticed on the bugged client you can click around and move the location of the tactical grid highlight
![bug tactical grid](https://user-images.githubusercontent.com/79132112/230277996-31501f41-4f20-4106-b4e7-759b93b90e6a.gif)

**Comment by Aedif** [comment]
Should be fixed in release [1.12.0](https://github.com/Aedif/tactical-grid/releases/tag/1.12.0)

The distances showingup on other clients was unintended. Should no longer happen.
