### ISSUE TITLE
[Feature Request] Set View Distance based on an individual Token's movement characteristic

### ISSUE THREAD

**Issue by Scooby-Goober** [Aedif/tactical-grid#14]
I see it's already possible to set individual grid distances for each token. It'd be cool if that could be automatically set to reflect something like a token's movement characteristic, so that it can be used to show standard move distance. Thanks!

**Comment by Aedif** [comment]
New settings added to use tokens/actors property to scale the view distance by: https://github.com/Aedif/tactical-grid/releases/tag/1.14.0
