### ISSUE TITLE
[Feature Request] Grid-independent Distance Label Size

### ISSUE THREAD

**Issue by LukasPrism** [Aedif/tactical-grid#15]
Would it be possible to unshackle the distance label font size from the scene grid? We use scenes from multiple sources, and as you can see when we jump from scene to scene the font size on the tokens varies wildly:

A House Divided – 200px grid size
<img width="857" alt="Screenshot 2023-08-21 at 2 53 32 PM" src="https://github.com/Aedif/tactical-grid/assets/104886594/2f5eace7-ca8e-4c74-9ed5-0c12408c2dc8">

Forgotten Adventures – 100px grid size
<img width="857" alt="Screenshot 2023-08-21 at 2 53 54 PM" src="https://github.com/Aedif/tactical-grid/assets/104886594/e4db87ab-4a42-4bc2-8490-bb6c3618a76b">

Many thanks!

**Comment by LukasPrism** [comment]
Actually I just noticed that drag ruler and the nameplate sizes also change based on grid pixel density. I wonder if there would be a blanket way to fix all of these 🤔

Let me know what you think – I'll close the issue if you don't think it's relevant to Tactical Grid. I guess it's just more obvious with the distances on the tokens.

**Comment by Aedif** [comment]
There is nothing to be "fixed" per say. If you look at the `CONFIG.canvasTextStyle` you'll find the default style used by all the pieces of text on the canvas. Some text has hard coded conditions such as this:

```js
  /**
   * Get the text style that should be used for this Token's tooltip.
   * @returns {string}
   * @protected
   */
  _getTextStyle() {
    const style = CONFIG.canvasTextStyle.clone();
    style.fontSize = 24;
    if (canvas.dimensions.size >= 200) style.fontSize = 28;
    else if (canvas.dimensions.size < 50) style.fontSize = 20;
    style.wordWrapWidth = this.w * 2.5;
    return style;
  }
  ```
  
  that modify the font size based on canvas dimensions in discrete steps.

It seems very much intentional. I can perhaps add some sort of font size scaling option but messing with all the numerous  contexts that text appears in Foundry is far beyond this module.

**Comment by LukasPrism** [comment]
Hmm yeah I’ll close the issue, it is bigger than this module. I do find it very odd that text size is based on grid pixel density and not just the grid size itself. It means the text isn’t consistent with token size from scene to scene. Token/grid size seems like a much more obvious visual benchmark than something that is invisible to the viewer like number of pixels per grid.
