### ISSUE TITLE
Hide Range/Cover display for dead tokens

### ISSUE THREAD

**Issue by txm3278** [Aedif/tactical-grid#16]
It would help remove clutter if these were hidden when moving a token.
![image](https://github.com/Aedif/tactical-grid/assets/25332081/456f94c2-c878-492a-9f75-67323242e0ee)

**Comment by dineshm72** [comment]
Agreed, or at least an option to hide defeated enemies.

**Comment by Aedif** [comment]
New option added in the latest release: https://github.com/Aedif/tactical-grid/releases/tag/1.17.0
