### ISSUE TITLE
[Feature Request] Infinite grid

### ISSUE THREAD

**Issue by Zamrod** [Aedif/tactical-grid#22]
Maybe there's a setting somewhere that I can't find but I'd like to use all the features of the module but still show an infinite grid all the time.

**Comment by Aedif** [comment]
What do you mean by 'infinite grid'? You mean you don't want the limtied grid view?

Make all the layers are unchecked
![image](https://github.com/Aedif/tactical-grid/assets/7693704/82742fee-0b50-4931-b7e0-c6c1d209f4f7)

**Comment by Aedif** [comment]
There are keybinds to toggle it as well.

**Comment by Zamrod** [comment]
Thanks. That works.
