### ISSUE TITLE
Show distance to other tokens using a button

### ISSUE THREAD

**Issue by stalker168** [Aedif/tactical-grid#28]
You can see the distance to other tokens when you move yours. It would be nice to be able to see the distance without having to move. For example, press Alt and the distance to them will appear on the tokens that you see.
Like the Hover Distance module from TheRipper93. But I would just like to have a correct distance calculation in hexes.

**Comment by Aedif** [comment]
Have you tried this?
![image](https://github.com/Aedif/tactical-grid/assets/7693704/ba1bb88d-a834-409b-b37f-4fceb48dd850)

**Comment by stalker168** [comment]
Yes, this is what I was looking for. Thank you!
