### ISSUE TITLE
Thrown weapons in dnd5e don't properly show long range

### ISSUE THREAD

**Issue by Zamrod** [Aedif/tactical-grid#30]
As shown in the screenshot below, when you hover over a thrown weapon it correctly shows the short range of the weapon but does not color the long range in orange. It works with ranged weapons but not thrown weapons.

![Screenshot 2024-03-08 042940](https://github.com/Aedif/tactical-grid/assets/12570777/9dc0a321-4a38-427c-beec-14d219d5ff36)

Foundry 11.315
Tactical Grid 1.24.0
dnd5e 3.0.4

**Comment by Aedif** [comment]
Fixed in [1.24.1](https://github.com/Aedif/tactical-grid/releases/tag/1.24.1)
