### ISSUE TITLE
Bug: cover calculation is shown from current location and not destination drag location

### ISSUE THREAD

**Issue by roi007leaf** [Aedif/tactical-grid#31]
when using pf2e perception for cover calculation cover calc seems wrong
![image](https://github.com/Aedif/tactical-grid/assets/17231451/a28ec700-5beb-435c-b309-c9567bf39929)

**Comment by Aedif** [comment]
I don't think I can do much about this on my end.

As far as I can tell TG is passing the token generated during drag to PF2e Perception  correctly, but for some reason it using the original.

You should probably direct this to the developer that module.
