### ISSUE TITLE
Consider dropping ATC cover code

### ISSUE THREAD

**Issue by caewok** [Aedif/tactical-grid#32]
Hi! I am the dev for Alt. Token Cover module.

Alt Token Cover v0.7.0 made some changes and now can display cover icons on a per-user basis. As such, I don't think Tactical Grid's display of cover icons is necessary if ATC is installed. So I recommend just removing `tokencover` (and `tokenvisibility`, which stopped handling cover awhile ago) from the options in [`computeCoverBonus`](url). Otherwise, I think the two modules will just end up displaying the same cover icons repeatedly.

If you did want to keep it or access cover calculations for other reasons, you can do that a few different ways:
- [`token.tokencover. coverPercentFromAttacker(attackingToken)`](https://github.com/caewok/fvtt-token-cover/blob/31339936ec67024259b4300126dc9ee110da7686/scripts/TokenCover.js#L117) This will get you the percent cover for the token.
- [`token.tokencover. coverTypesFromAttacker(attackingToken)`](https://github.com/caewok/fvtt-token-cover/blob/31339936ec67024259b4300126dc9ee110da7686/scripts/TokenCover.js#L128) This will get you one or more defined CoverTypes, which represent system-specific rules for cover.
- [`attackingToken.tokencover.coverCalculator.targetCover(targetToken)`](https://github.com/caewok/fvtt-token-cover/blob/31339936ec67024259b4300126dc9ee110da7686/scripts/CoverCalculator.js#L127) This is the old, deprecated way to get an enumerated cover type: none (0), low (1), medium (2), high (3).

**Comment by Aedif** [comment]
https://github.com/Aedif/tactical-grid/releases/tag/1.25.0
