### ISSUE TITLE
Grid Not Showing - but I get an error

### ISSUE THREAD

**Issue by ClayGolemDM** [Aedif/tactical-grid#36]
Foundry V12 Build 327
DnD 5th Ed - Build 3.2.0

Tactical Grid does not show up (it did, then stopped and won't come back). Have changed all the settings to see if it works in some instances and not others, but it just hates me now. This is ONLY the show grid function - I have "On Control" and "On Hover" on, and have tried switching them off in turn to narrow down the issue (I really don't understand how you do any of this stuff!).

Obviously have tried updating, restarting Foundry, reloading World.

Console error: 
<img width="406" alt="Screenshot 2024-06-14 080335" src="https://github.com/Aedif/tactical-grid/assets/172749575/247d478a-d581-435a-b955-6567ebd24e10">

**Comment by Aedif** [comment]
https://github.com/Aedif/tactical-grid/releases/tag/1.27.2

This was cause by `Grid Line Width` setting being set on v12. Since v12 now natively supports setting grid width the setting has been removed when loading the module from a v12 client.

**Comment by ClayGolemDM** [comment]
Tested and working perfectly! Thank you for the super-fast fix.
