### ISSUE TITLE
Bug: Calculations for diagnal seem incorrect

### ISSUE THREAD

**Issue by MaineKnight** [Aedif/tactical-grid#40]
Foundry: 331 version 12 stable
Tactical Grid: 1.28.0
Game System: Dungeons and Dragons - 4.0.2 (tested in 5e 2014 edition as well)
Core: Set to equadistant 1 (each square counts as 5' regardless of movement path)
 
It appears to be doubling every other square.

If I use the hover feature or the ruler feature dragging the token I am getting the same incorrect distances.

* Drag 1 square diagonal (5')
* Drag 1 more square in the same diagonal direction and the distance jumps by 10' instead of 5'
* Drag 1 more square in the same diagonal direction and the distance jumps by 5'
* Drag 1 more square in the same diagonal direction and the distance jumps by 10' instead of 5'

2 x 5' squares + 2 x 10' squares = 30'

It should be:

* Drag 1 square diagonal (5')
* Drag 1 more square in the same diagonal direction and the distance jumps by 5'
* Drag 1 more square in the same diagonal direction and the distance jumps by 5'
* Drag 1 more square in the same diagonal direction and the distance jumps by 5'

4 x 5' squares = 20'

**Comment by Aedif** [comment]
![image](https://github.com/user-attachments/assets/7d1dd6ca-e8fb-4bb5-b541-72671b69f8bb)

Set the Diagonal Multiplier to 1

**Comment by MaineKnight** [comment]
Perfect, I missed that setting somehow.  Thanks,
