### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by MaineKnight** [Aedif/tactical-grid#41]
Not sure if this is possible to do. We play in person using a laptop for the DM and a map tv for the players. Currently, I have to switch to the players session screen in my browser to activate the distances for them. It would be helpful if I could toggle to show the distances. So if I turn on the toggle in the navigation bar on the left then when I press the button both myself and the players screen would show the distances, if I turn it off then the DM screen and player session screen would work separate. This way when the players ask for the distance on things I can show them by doing it on my DM screen, verses jumping screens.

**Comment by Aedif** [comment]
Interesting. Shouldn't be too hard to implement. WIll have a go.

**Comment by MaineKnight** [comment]
Great, thanks. Let me know when it's been added and I'll test it

**Comment by Aedif** [comment]
https://github.com/Aedif/tactical-grid/releases/tag/2.6.0
