### ISSUE TITLE
[Feature request] Add an ability to remove "Broadcast measurements" from the toolbar

### ISSUE THREAD

**Issue by TrofimSelbs** [Aedif/tactical-grid#42]
Hello! Let me start by saying thank you. Your module has finally enabled me to go fully gridless and I adore it for that. I come here asking for the ability to remove the button "Broadcast Measurements" from the sidebar. Just a toggle in the module's settings. Thank you in advance

**Comment by Aedif** [comment]
https://github.com/Aedif/tactical-grid/releases/tag/1.31.0
