### ISSUE TITLE
[Feature Request] Show token distances from selected token

### ISSUE THREAD

**Issue by Jorgixhallo** [Aedif/tactical-grid#5]
When pressing some hotkey (or maybe hovering/targeting a token) we could show distance from the selected/own token to targets around us.

This could help players not having to pick measurement tool to check distances between them and enemy when we have the  grid configured relatively small but they have some spell/effect that has bigger range.

**Comment by Aedif** [comment]
That's a pretty good idea.

First iteration of this feature is available in release [1.7.0](https://github.com/Aedif/tactical-grid/releases/tag/1.7.0)
