### ISSUE TITLE
Distance seems to be rounded when using "Display Distances"

### ISSUE THREAD

**Issue by BrotherSharper** [Aedif/tactical-grid#6]
Hello!
Thanks for the amazing mod!

I noticed that the module rounds up distances to the nearest full number when using the Display Distances hotkey.
Japan uses the metric system for games like D&D where 1 square = 1.5 meters.

Yes, I know this seems weird, convoluted, stupid, and or otherwise completely unnecessary, but WotC has decided to go that route for international releases. It would be amazing if you could make it so the distance appears appropriately even when using decimals.
![image](https://user-images.githubusercontent.com/41280723/223305309-517aeedf-d822-44dd-bf6d-1eb9716ddbc6.png)

In the above image, the grid is set to 1.5m per square. The 3m character is fine, but 2m should be 1.5m and 5m should be 4.5m etc.

**Comment by Aedif** [comment]
'ello Yojimbo 😉 

As of release https://github.com/Aedif/tactical-grid/releases/tag/1.9.0 you can specify decimal precision. Set it to 1 should do the trick for you:

`Configure Settings` > `Measurement` > `Precision`

**Comment by BrotherSharper** [comment]
Heya! Thank you!

This does exactly what I wanted!
The added extra bit of font size was also amazing.

I do not really wish to bother you further, but would it be possible to also make diagonals count as one square as well?
As you can see below, 3.4m should be 3m and 4.7m should be 4.5m!

![image](https://user-images.githubusercontent.com/41280723/223418489-113882e3-8741-4c2c-ba30-dc28b100ae56.png)

**Comment by Aedif** [comment]
Use `Display Distances (Grid Spacing)` instead. That control meaures distances in grid space increments

**Comment by BrotherSharper** [comment]
You are absolutely right, thank you, good sir!
