### ISSUE TITLE
Feature Request:  Integration with Stairways(Teleport) Module

### ISSUE THREAD

**Issue by MotoMoto1234** [Aedif/tactical-grid#7]
Can you make it so that the tactical grid always shows in stairways mode with Stairways(teleport) module enabled?  Similar how you have the grid show for journal pin tool?

**Comment by Aedif** [comment]
As of release [1.9.0](https://github.com/Aedif/tactical-grid/releases/tag/1.9.0) the TG should now properly interact with layers added by other modules.
